[build]
  command = "node pre-build.js && npm run build"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "18"
  IMAGES_DIR = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Asset handling
[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Copy images to correct location during build